### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by dobrynski** [doubleO8/enigma2_http_api#1]
Any chance of making this library Python3 compatible? I'd like to try my hand at making an Enigma2 media player platform for Home Assistant.

Regards,
Michal

**Comment by doubleO8** [comment]
Hi Michal,

currently there is no python3 support planned.
The enigma2 platform is still python2 only and **enigma2_http_api** scripts are supposed to be executable on the enigma2 host thus there is no need for python3 support.

This should not stop you from sending pull requests with python3 support patches :)

**Comment by dobrynski** [comment]
The changes are minimal and I believe backwards compatible (I will check). Just have to learn how to use github and do PR's.

I had no idea that this was intended to run on the Enigma device and have successfully been using it remotely. Works great!

**Comment by doubleO8** [comment]
Michal, that actually *is* the intended usage ;)

**enigma2_http_api**'s main goal is providing a thin wrapper library for the [Enigma2:WebInterface](https://dream.reichholf.net/wiki/Enigma2:WebInterface).
Using the library may help controlling enigma2 based STBs either from the enigma2 device itself or from a remote host.

My very own use cases are

1. Automated recording of movies and series using a cron job on a remote server
2. Automated fetching of recordings using a cron job on a remote server
3. Being able to log on to the enigma2 device via SSH in order to schedule recordings (this is where the scripts need to be run on the device itself :)
